// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrOQThbmafvocmmb-0OWYKD8q3kqUFldM',
    appId: '1:1011436910772:web:d08c62be7ddde3ae2f7fe1',
    messagingSenderId: '1011436910772',
    projectId: 'elmwslaty-final',
    authDomain: 'elmwslaty-final.firebaseapp.com',
    storageBucket: 'elmwslaty-final.appspot.com',
    measurementId: 'G-NKV01PDMFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_aA34SjrQGzVvcAWHqtT6ArD63m_7aKE',
    appId: '1:1011436910772:android:473b36684f7deb802f7fe1',
    messagingSenderId: '1011436910772',
    projectId: 'elmwslaty-final',
    storageBucket: 'elmwslaty-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmrz0h4ZckqOdgthWbLBf32MNdU-vj874',
    appId: '1:1011436910772:ios:80e877f3bd59221d2f7fe1',
    messagingSenderId: '1011436910772',
    projectId: 'elmwslaty-final',
    storageBucket: 'elmwslaty-final.appspot.com',
    androidClientId: '1011436910772-1b79p989s64hjb72v64qu88bcueuloi4.apps.googleusercontent.com',
    iosClientId: '1011436910772-al6qr8f37fkfi2eu420nit4pjvjtsjua.apps.googleusercontent.com',
    iosBundleId: 'com.ahmed.elmwslaty',
  );
}
